language: node_js

node_js:
  - node

cache:
  directories:
    node_modules

script:
  - npm run lint
  - npm run test

deploy:
  provider: heroku
  api_key:
    secure: azAYGhdtsaP7nhMSCkH+8BgwvEs1WgPcz5O9k1Btgz4rOYk+a2xtUEtgsp4YO5IZTtQU5KJp9513S6R+seS7UObwYX+ETs4arNGdv4/h7eE0+cDYZhf/uLiYUtyNhNmSbXmcLTWPf6jSa2sCFqTxBJDSCqrDKWCHZUQUW2L+fAfgznuzLDg1iZAU5eTDUCI0k6gN2QpEHljLWTyfX4tXnsEu5U0KcOqw9T748XN0zPm6axaE0ausWeTBRj1bQOG7zAe0nOVDU4AtIQCnxOczvkIENcl3QDjfC3/gsImWn889PcHF7AcrWZqsa5AJ8OHemZ+U2rMVsMoZVj/AV9VNVw21xXCP4wKN46hbO8zVjv84DLXEkBx97qTtL/90pytNA+EsNywURxXiqPaER3ostd9VYsPdDKnsDd3jPqTYnlIG/5YpboGtvq/ohEwqBt4xacbev+aag5YovMGwG7dmw3eWgViCgC0iOzxNQoEjXHQeo+pT5PVd5POyP3VX1TG5gy8wjzxac9LgqxtjOnX0trOxAyJhjJVyk3tx9SByzmhkmlZdgyO79eGMKs0dDcZsLjduIzaZOc2Hje97bUxFR7YSvPqAUzQX8XFJim3hnjuQq2VV3haf07M5xNA/am1L7wY+jTARtAG+3eWOA3X6vlSraIVmcCDhQA6/SZZOr5w=
  app:
    master: cucalendar-staging
    production: cucalendar-production

notifications:
  email: false
